[package]
name = "with-log4rs"
version = "0.1.0"
edition = "2024"

[dependencies]
serde.workspace = true
serde_json.workspace = true
tokio.workspace = true
chrono.workspace = true
log = { version = "0.4.27" }
anyhow = { version = "1.0" }
log4rs = { version = "1.3" }
