[package]
name = "with-tracing"
version = "0.1.0"
edition = "2024"

[dependencies]
serde.workspace = true
serde_json.workspace = true
tokio.workspace = true
chrono.workspace = true
tracing = { version = "0.1.41" }
tracing-subscriber = { version = "0.3.19" }
